export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQ_PICS_PENDING = 'REQ_PICS_PENDING'
export const REQ_PICS_SUCCESS = 'REQ_PICS_SUCCESS'
export const REQ_PICS_FAILED = 'REQ_PICS_FAILED'

export const REQ_BRANCH_PENDING = 'REQ_BRANCH_PENDING'
export const REQ_BRANCH_SUCCESS = 'REQ_BRANCH_SUCCESS'
export const REQ_BRANCH_FAILED = 'REQ_BRANCH_FAILED'

export const REQ_NAMES_PENDING = 'REQ_NAMES_PENDING'
export const REQ_NAMES_SUCCESS = 'REQ_NAME_SUCCESS'
export const REQ_NAMES_FAILED = 'REQ_NAMES_FAILED'

export const REQ_CATEGORY_PENDING = 'REQ_CATEGORY_PENDING'
export const REQ_CATEGORY_SUCCESS = 'REQ_CATEGORY_SUCCESS'
export const REQ_CATEGORY_FAILED = 'REQ_CATEGORY_FAILED'

export const REQ_CATEGORYONE_PENDING = 'REQ_CATEGORYONE_PENDING'
export const REQ_CATEGORYONE_SUCCESS = 'REQ_CATEGORYONE_SUCCESS'
export const REQ_CATEGORYONE_FAILED = 'REQ_CATEGORYONE_FAILED'

export const REQ_PERSONS_PENDING = 'REQ_PERSONS_PENDING'
export const REQ_PERSONS_SUCCESS = 'REQ_PERSONS_SUCCESS'
export const REQ_PERSONS_FAILED = 'REQ_PERSONS_FAILED'

export const REQ_FILES_PENDING = 'REQ_FILES_PENDING'
export const REQ_FILES_SUCCESS = 'REQ_FILES_SUCCESS'
export const REQ_FILES_FAILED = 'REQ_FILES_FAILED'
